yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),

    path('logout/', LogoutView.as_view(
        template_name='users/logged_out.html'), name='logout'),

    path('login/', LoginView.as_view(
        template_name='users/login.html'), name='login'),

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change_form.html'),
        name='password_change'),

    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),

    path('password_reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html'),
        name='password_reset'),

    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='index')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name='ЧПУ'
    )
    description = models.TextField(
        max_length=400,
        verbose_name='Описание'
    )

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группу'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        max_length=400,
        help_text='Введите текст поста',
        verbose_name='Текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }

yatube/users/forms.py
# users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'


class About(TemplateView):
    template_name = 'about/index.html'

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .utils import paginate_page
from .forms import PostForm
from .models import Group, Post

User = get_user_model()


def index(request):
    post_list = Post.objects.select_related('group', 'author')
    page_obj = paginate_page(request, post_list)
    context = {'page_obj': page_obj, }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('group')
    page_obj = paginate_page(request, posts)
    context = {'group': group, 'page_obj': page_obj}
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginate_page(request, post_list)
    context = {'page_obj': page_obj, 'author': author}
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {'post': post, }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        create_post = form.save(commit=False)
        create_post.author = request.user
        create_post.save()
        return redirect('posts:profile', create_post.author)
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=edit_post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'is_edit': True}
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я Lfyz</h1>
<p>
  Тут я размещу информацию о себе, используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %} 

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Технологии</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"<hr>
    На этой странице можно рассказать, какие программные инструменты вы применили для создания этого сайта, какие навыки вам помогли, с чем вы хорошо разобрались, а с чем — не очень. Картинки и нестандартные подходы приветствуются: эта страница может получиться очень интересной.
    </p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
      <meta name="msapplication-TileColor" content="#da532c">
      <meta name="theme-color" content="#ffffff">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <title>{% block title %}{% endblock %}</title>
      {% block header %}{% endblock %}
  </head>
    <body> 
    {% include 'includes/header.html' %}
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock %}
      </div>
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>©{{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/form.html
{% load user_filters %}
{% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}            
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
{% endif %}
<form method="post" {% if action_url %} action="{% url action_url %}" {% endif %}>
  {% csrf_token %}
  {% for field in form %}<div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item"> 
              <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
            </li>
          <li class="nav-item">
              <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
            </li>
        {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить пароль</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link">Пользователь: {{ user.username }}</a>
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
<!-- templates/posts/includes/paginator.html -->
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
<div class="row justify-content-center">
<div class="col-md-8 p-5">
  <div class="card">
    <div class="card-header">{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}</div>
    <div class="card-body">
        {% include 'includes/form.html' %}
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">{% if is_edit %}Сохранить{% else %}Добавить{% endif %}</button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества: {{ group.title }}{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
<p>{{ group.description|linebreaks }}</p>
{% for post in page_obj %}
<ul>
  <li>
    Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:'d E Y' }}
  </li>
</ul>
    {{ post.text|linebreaks }}
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  <div>{% include 'includes/paginator.html' %}</div>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %} <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a><br>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  <div>
    {% include 'includes/paginator.html' %}
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
      <li class="list-group-item">
        Группа:
        {% if post.group %}
        {{ post.group.title }}
        {% else %}
        ---Пусто---
        {% endif %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {% if post.author.get_full_name %}{{ post.author.get_full_name }}{% else %}{{ post.author }}{% endif %}
      </li>
      <li class="list-group-item">
        Всего постов автора: {{ posts_count }}
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>{{ post.text | linebreaksbr }}</p>
  {% if request.user == post.author %}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">редактировать запись</a>
  {% endif %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
    {% if author.get_full_name %}
        {{ author.get_full_name }}
    {% else %}
        {{ author }}
    {% endif %} профайл пользователя
{% endblock %}
{% block content %}
<h1>Все посты пользователя {% if author.get_full_name %}{{ author.get_full_name }}{% else %}{{ author }}{% endif %}</h1>
<h3>Всего постов: {{ page_obj.paginator.count }}</h3>
{% for post in page_obj %}
    <ul>
        <li>
        Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
    </ul>
    <p>{{ post.text | linebreaksbr }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    <br>
    {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
    <div>{% include 'includes/paginator.html' %}</div>
</div>
{% endblock %}

yatube/templates/users/logged_out.html
<!-- templates/users/logged_out.html -->
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
        <div class="card-header">Выход</div>
        <div class="card-body">
          <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
        </div>
    </div>
  </div>
</div>
{% endblock %} 

yatube/templates/users/login.html
<!-- templates/users/login.html -->
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% include 'includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Войти</button>
            <a href="{% url 'password_reset' %}" class="btn btn-link">Забыли пароль?</a>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
<!-- templates/users/password_change_done.html -->
{% extends 'base.html' %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Пароль изменён</div>
      <div class="card-body">
        <p>Пароль изменён успешно</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_change_form.html
<!-- templates/users/password_change_form.html -->
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Изменить пароль</div>
      <div class="card-body">
          {% include 'includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Изменить пароль</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
<!-- templates/users/password_reset_complete.html -->
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Восстановление пароля завершено</div>
      <div class="card-body">
        <p>Ваш пароль был сохранен. Используйте его для входа</p>
        <a href="{% url 'login' %}">войти</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
<!-- templates/users/password_reset_confirm.html -->
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% if validlink %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Введите новый пароль</div>
      <div class="card-body">
          {% include 'includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Назначить новый пароль</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Ошибка</div>
      <div class="card-body">
        <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
<!-- templates/users/password_reset_done.html -->
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Отправлено письмо</div>
      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
<!-- templates/users/password_reset_form.html -->
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались</div>
        <div class="card-body">
          {% include 'includes/form.html' %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">Сбросить пароль</button>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</div>
{% endblock %}

yatube/templates/users/signup.html
<!-- templates/users/signup.html -->
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 